-- ============================================
-- Schema: enquiries
-- Tables: contactmessages, contactmessageresponses
-- Includes: primary keys, foreign key, indexes
-- ============================================

CREATE TABLE IF NOT EXISTS enquiries.contactmessages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname    VARCHAR(20),
    lastname     VARCHAR(20),
    email        VARCHAR(50),
    company      VARCHAR(100),
    message      VARCHAR(1000),
    createdat    TIMESTAMPTZ DEFAULT now(),
    status       VARCHAR(10),
    universalid  UUID NOT NULL
);

CREATE TABLE IF NOT EXISTS enquiries.contactmessageresponses (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contactmessageid  BIGINT,
    message           VARCHAR(1000),
    createdat         TIMESTAMPTZ DEFAULT now(),
    status            VARCHAR(10),
    universalid       UUID NOT NULL,
    CONSTRAINT fk_contactmessage_messageresponse
        FOREIGN KEY (contactmessageid)
        REFERENCES enquiries.contactmessages (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- ============================================
-- Indexes
-- ============================================

CREATE INDEX IF NOT EXISTS idx_contactmessages_universalid
    ON enquiries.contactmessages (universalid);

CREATE INDEX IF NOT EXISTS idx_contactmessageresponses_universalid
    ON enquiries.contactmessageresponses (universalid);