ALTER TABLE IF EXISTS enquiries.contactmessages
    ADD COLUMN IF NOT EXISTS createdby VARCHAR(10),
    ADD COLUMN IF NOT EXISTS updatedby VARCHAR(10),
    ADD COLUMN IF NOT EXISTS updatedat TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE IF EXISTS enquiries.contactmessageresponses
    ADD COLUMN IF NOT EXISTS createdby VARCHAR(10),
    ADD COLUMN IF NOT EXISTS updatedby VARCHAR(10),
    ADD COLUMN IF NOT EXISTS updatedat TIMESTAMPTZ NOT NULL DEFAULT now();
