name: Deploy DNS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - prod
          - test

  pull_request:
    branches:
      - '**'
    paths:
      - 'infrastructure/dns/**'
      - '.github/workflows/deploy-ui-dns.ci.yml'
  
  push:
    branches:
      - main
    paths:
      - 'infrastructure/dns/**'
      - '.github/workflows/deploy-ui-dns.ci.yml'

jobs:
  deploy-dns:
    uses: nexsware/modules/.github/workflows/deploy-dns.yml@main
    secrets: inherit
    with:
      domain_id: 3394034
      dns_records: '[{ name = "nexsware.com", type = "A", value = "172.232.111.148" }, { name = "www.nexsware.com", type = "A", value = "172.232.111.148" }]'
      ttl_sec: 300