name: Deploy Vultr Database Firewall
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy'
                required: true
                default: 'test'
                type: choice
                options:
                - prod
                - test
    push:
        branches:
        - main
        paths:
        - '.github/workflows/deploy-vultr-db-fwl-ci.yml'
jobs:
    deploy-firewall:
        uses: nexsware/modules/.github/workflows/deploy-vultr-firewall.yml@main
        secrets: inherit
        with:
            environment: "${{ inputs.environment}}"
            description: "Database Firewall for Nexsware infrastructure"
            firewall_type: "database"
            allow_ssh_from: "10.0.0.0/24"  # Allow SSH from VPC subnet