name: Deploy Vultr Database VPS
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy'
                required: true
                default: 'test'
                type: choice
                options:
                - prod
                - test
    push:
        branches:
        - main
        paths:
        - '.github/workflows/deploy-vultr-db-fwl-ci.yml'

jobs:
    deploy-database-vps:
        uses: nexsware/modules/.github/workflows/deploy-vultr-postgres-self-hosted.yml@main
        secrets: inherit
        with:
            environment: "${{ inputs.environment}}"
            region: "jnb"
            plan: "vc2-1c-2gb"
            os_id: 2284  # Ubuntu 24.04 x64  LTS
            label: "Vultr-database-server"
            postgres_version: "18"
            listen_address: "*"
            port: "5432"
            databases: Safii
            service_account_username: "svc-safii-api"
            firewall_group_id: "b0cb0f2f-7217-4bb6-9f66-2f30b68b0926" # Reference to the database firewall group created separately
            vpc_ids: "6836516b-2681-4914-8f57-f9a1dc3e241e" # Reference to the VPC created separately


            

            