name: Deploy Vultr Database VPS
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy'
                required: true
                default: 'test'
                type: choice
                options:
                - prod
                - test
    push:
        branches:
        - main
        paths:
        - '.github/workflows/deploy-vultr-db-fwl-ci.yml'

jobs:
    deploy-database-vps:
        uses: nexsware/modules/.github/workflows/deploy-vultr-postgres-self-hosted.yml@main
        secrets: inherit
        with:
            environment: "${{ inputs.environment}}"
            region: "jnb"
            plan: "vc2-1c-2gb"
            os_id: 2284  # Ubuntu 24.04 x64  LTS
            label: "Vultr-database-server"
            postgres_version: "18"
            
            