name: Deploy UI Firewall

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy'
                required: true
                type: choice
                options:
                - prod
                - test
    pull_request:
        branches:
        - '**'
        paths:
        - '.github/workflows/deploy-ui-fwl.ci.yml'
    push:
        branches:
        - main
        paths:
        - '.github/workflows/deploy-ui-fwl.ci.yml'
jobs:
    deploy-firewall:
        uses: nexsware/modules/.github/workflows/deploy-firewall.yml@main
        secrets: inherit
        with:
            instance_id: "89359554"
            environment: "${{ inputs.environment || 'test' }}"
            application_name: "nexsware-ui"
            allow_ssh_from: "172.232.107.171/32"  # Your IP
