name: Deploy Vultr Web Firewall
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy'
                required: true
                default: 'test'
                type: choice
                options:
                - prod
                - test
    push:
        branches:
        - main
        paths:
        - '.github/workflows/deploy-vultr-fwl-ci.yml'

jobs:
    deploy-firewall:
        uses: nexsware/modules/.github/workflows/deploy-vultr-firewall.yml@main
        secrets: inherit
        with:
            environment: "${{ inputs.environment}}"
            description: "API Firewall for Nexsware infrastructure"
            firewall_type: "api"
            app_subnet: "10.0.0.0/26"  # Allow access from VPC subnet
            allow_ssh_from: "10.0.0.128/26"  # Allow SSH from VPC subnet
            app_port: "5000"
