name: Provision Vultr Bastion Host

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy"
                required: true
                default: "test"
                type: choice
                options:
                    - prod
                    - test

    push:
        branches:
            - main
        paths:
            - ".github/workflows/Deploy-vultr-bastion-instance-ci.yml"
jobs:
    deploy-bastion:
        name: Deploy Vultr Bastion Host
        uses: nexsware/modules/.github/workflows/deploy-vultr-instance.yml@main
        secrets:
            VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
        with:
            environment: ${{ inputs.environment}}
            region: "jnb"
            plan: "vc2-1c-2gb"  # Adjust as needed
            os_id: "215"  # Ubuntu 22.04 x64
            label: "Vultr-bastion-host"